name: CI

on:
  workflow_dispatch:
  
jobs:
  fetch-api-data:
    runs-on: windows-latest
    steps:
      - name: Fetch API Data ðŸ“¦
        uses: JamesIves/fetch-api-data-action@releases/v1
        with:
          ENDPOINT: https://coronavirus.bg/stats.json
      - name: Check env vars
        run:  gci "env:"

